[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
dex_solana = "6m2CDdhRgxpH4WjvdzxAYbGxwdGUz5MziiL5jek2kBma"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "PATH_TO_YOUR_WALLET"
